### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by fi-ya** [tech-for-better/in-common#26]
Great work folks! 🎉  Just a reminder, please do update your README.md as you go along. Perhaps at the end of each day? ❓

**Comment by Alisyad9** [comment]
> Great work folks! 🎉 Just a reminder, please do update your README.md as you go along. Perhaps at the end of each day? ❓
Here is the link to our Documentation: 
https://quickest-sphere-0d2.notion.site/In-common-Project-b888c43f436645d2998ef3fbc1a4347a
